DATASET:
  desc: fashion_mnist, cifar10 or cifar100
  value: fashion_mnist
MODEL:
  desc: LENET, RESNET18,LENET_SLIM, RESNET18_SLIM
  value: LENET

RANDOM_SEED:
  desc: random seed
  value: 3333
NUM_EPOCHS:
  value: 100
BATCH_SIZE:
  value: 100
USE_ROUTING:
  value: True
LR_INITIAL:
  value: 0.001
DROPOUT_RATE:
  value: 0.45
NUM_ROUTES_0:
  value: 2
NUM_ROUTES_1:
  value: 2
DECOUPLE_ROUTING_GRADIENTS:
  value: True
ROUTING_LOSS_WEIGHT:
  value: 1
WEIGHT_DECAY_METHOD:
  desc: StepDecay, ExponentialDecay, EarlyStopping or TimeBasedDecay
  value: TimeBasedDecay
ROUTING_LOSS_WEIGHT_DECAY:
  value: 0
ROUTING_EARLY_STOPPING_STEP:
  desc: Number of steps before stopping training of the routing layers, if EarlyStopping decay method is used
  value: 0

INFORMATION_GAIN_SOFTMAX_TEMPERATURE_INITIAL:
  value: 25
INFORMATION_GAIN_SOFTMAX_TEMPERATURE_DECAY_RATE:
  value: 0.9999
ADD_GUMBEL_NOISE:
  value: False
INFORMATION_GAIN_BALANCE_COEFFICIENT_INITIAL:
  value: 5
INFORMATION_GAIN_BALANCE_COEFFICIENT_DECAY_RATE:
  value: 1
RANDOM_ROUTING_STEPS:
  desc: Number of steps in the beginning of the training where random routing will be used
  value: 5400